from agentframe.generators.base import BaseGenerator
from agentframe.graph.store import Graph


def _gcp_service_yaml(app_name: str, project_id: str, region: str) -> str:
    return f"""\
# deploy/gcp/service.yaml — DO NOT EDIT (generated by AgentFrame DeploymentGenerator)
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {app_name}
  namespace: {project_id}
  labels:
    cloud.googleapis.com/location: {region}
spec:
  template:
    spec:
      containers:
        - image: gcr.io/{project_id}/{app_name}:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_DATABASE_URL
              value: "${{APP_DATABASE_URL}}"
            - name: SECRET_KEY
              value: "${{SECRET_KEY}}"
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
      containerConcurrency: 80
      timeoutSeconds: 300
  traffic:
    - percent: 100
      latestRevision: true
"""


def _gcp_deploy_sh(app_name: str, project_id: str, region: str) -> str:
    return f"""\
#!/bin/bash
# deploy/deploy_gcp.sh — DO NOT EDIT (generated by AgentFrame DeploymentGenerator)
set -euo pipefail

PROJECT_ID="${{1:-{project_id}}}"
SERVICE_NAME="{app_name}"
REGION="{region}"
IMAGE="gcr.io/${{PROJECT_ID}}/${{SERVICE_NAME}}:latest"

echo "Building image: $IMAGE"
docker build -t "$IMAGE" .

echo "Pushing image..."
docker push "$IMAGE"

echo "Deploying to Cloud Run..."
gcloud run deploy "$SERVICE_NAME" \\
  --image "$IMAGE" \\
  --region "$REGION" \\
  --platform managed \\
  --allow-unauthenticated \\
  --set-env-vars "APP_DATABASE_URL=${{APP_DATABASE_URL}},SECRET_KEY=${{SECRET_KEY}}"

echo "Done. Service URL:"
gcloud run services describe "$SERVICE_NAME" --region "$REGION" --format "value(status.url)"
"""


def _aws_apprunner_yaml(app_name: str, region: str) -> str:
    return f"""\
# deploy/aws/apprunner.yaml — DO NOT EDIT (generated by AgentFrame DeploymentGenerator)
version: 1.0
runtime: python311
build:
  commands:
    build:
      - pip install -e .
run:
  command: uvicorn main_prod:app --host 0.0.0.0 --port 8080
  network:
    port: 8080
    env: APP_PORT
  env:
    - name: APP_DATABASE_URL
      value: "${{APP_DATABASE_URL}}"
    - name: SECRET_KEY
      value: "${{SECRET_KEY}}"
"""


def _aws_deploy_sh(app_name: str, region: str) -> str:
    return f"""\
#!/bin/bash
# deploy/deploy_aws.sh — DO NOT EDIT (generated by AgentFrame DeploymentGenerator)
set -euo pipefail

SERVICE_NAME="{app_name}"
REGION="{region}"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
ECR_REPO="${{ACCOUNT_ID}}.dkr.ecr.${{REGION}}.amazonaws.com/${{SERVICE_NAME}}"

echo "Logging in to ECR..."
aws ecr get-login-password --region "$REGION" | \\
  docker login --username AWS --password-stdin "${{ACCOUNT_ID}}.dkr.ecr.${{REGION}}.amazonaws.com"

echo "Building and pushing image..."
docker build -t "${{ECR_REPO}}:latest" .
docker push "${{ECR_REPO}}:latest"

echo "Updating App Runner service..."
aws apprunner update-service \\
  --service-arn "$(aws apprunner list-services --region "$REGION" --query "ServiceSummaryList[?ServiceName==\\'$SERVICE_NAME\\'].ServiceArn" --output text)" \\
  --source-configuration "ImageRepository={{ImageIdentifier=${{ECR_REPO}}:latest,ImageRepositoryType=ECR}}"

echo "Done."
"""


class DeploymentGenerator(BaseGenerator):
    """Generates cloud deployment configs for GCP Cloud Run and AWS App Runner."""

    def generate(self, graph: Graph) -> dict[str, str]:
        files: dict[str, str] = {}
        integrations = graph.list_nodes("integration")

        app_name = "agentframe-app"

        # GCP Cloud Run
        gcp_nodes = [n for n in integrations if n.attrs.get("provider") == "gcp_cloudrun"]
        if gcp_nodes:
            gcp = gcp_nodes[0]
            project_id = gcp.attrs.get("project_id", "my-gcp-project")
            region = gcp.attrs.get("region", "us-central1")
            files["../deploy/gcp/service.yaml"] = _gcp_service_yaml(app_name, project_id, region)
            files["../deploy/deploy_gcp.sh"] = _gcp_deploy_sh(app_name, project_id, region)

        # AWS App Runner
        aws_nodes = [n for n in integrations if n.attrs.get("provider") == "aws_apprunner"]
        if aws_nodes:
            aws = aws_nodes[0]
            region = aws.attrs.get("region", "us-east-1")
            files["../deploy/aws/apprunner.yaml"] = _aws_apprunner_yaml(app_name, region)
            files["../deploy/deploy_aws.sh"] = _aws_deploy_sh(app_name, region)

        return files
