from agentframe.generators.base import BaseGenerator
from agentframe.graph.store import Graph

_DOCKERFILE = """\
# Dockerfile — DO NOT EDIT (generated by AgentFrame DockerfileGenerator)
FROM python:3.11-slim
WORKDIR /app

# Install dependencies first (layer cache)
COPY pyproject.toml .
RUN pip install --no-cache-dir -e .

# Copy application code
COPY . .

# main_prod.py calls alembic upgrade head on startup via lifespan handler
CMD ["uvicorn", "main_prod:app", "--host", "0.0.0.0", "--port", "8080"]
"""

_DOCKERIGNORE = """\
.venv
__pycache__
*.pyc
*.pyo
.pytest_cache
.agentframe_key
agentframe.db
*.db
.env
.git
.gitignore
"""

_DOCKER_COMPOSE = """\
# docker-compose.yml — for local development with Postgres
version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: agentframe_app
      POSTGRES_USER: agentframe
      POSTGRES_PASSWORD: localdev
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_DATABASE_URL: postgresql://agentframe:localdev@db:5432/agentframe_app
      DATABASE_URL: sqlite:///./agentframe.db
      SECRET_KEY: dev-secret-change-in-prod
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn demo_app.main:app --host 0.0.0.0 --port 8080 --reload

volumes:
  pg_data:
"""


def _render_env_example(graph: Graph) -> str:
    from agentframe.database.connection import get_engine
    try:
        from agentframe.secrets.vault import EncryptedVault
        from agentframe.secrets.models import SecretNode
        engine = get_engine("sqlite:///:memory:")
        vault = EncryptedVault(engine)
        secrets = vault.list_all()
    except Exception:
        secrets = []

    lines = [
        "# .env.example — copy to .env and fill in values",
        "# Never commit .env to version control",
        "",
        "# AgentFrame graph database",
        "DATABASE_URL=sqlite:///./agentframe.db",
        "",
        "# App data database (SQLite for dev, Postgres/Neon for prod)",
        "APP_DATABASE_URL=sqlite:///./app.db",
        "",
        "# Vault encryption key (generate with: python3 -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\")",
        "AGENTFRAME_SECRET_KEY=",
        "",
        "# Application secrets",
    ]

    for s in secrets:
        lines.append(f"# {s.description}" if s.description else f"# Required by: {', '.join(s.required_by)}")
        lines.append(f"{s.env_var}=")

    if not secrets:
        lines.append("SECRET_KEY=change-me")

    return "\n".join(lines) + "\n"


class DockerfileGenerator(BaseGenerator):
    def generate(self, graph: Graph) -> dict[str, str]:
        return {
            "../Dockerfile": _DOCKERFILE,
            "../.dockerignore": _DOCKERIGNORE,
            "../docker-compose.yml": _DOCKER_COMPOSE,
            "../.env.example": _render_env_example(graph),
        }
