from agentframe.generators.base import BaseGenerator
from agentframe.graph.store import Graph

_ALEMBIC_INI = """\
# alembic.ini — managed by AgentFrame MigrationGenerator
[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os

# Read DATABASE_URL from environment (set for app data, not agentframe graph)
sqlalchemy.url = %(APP_DATABASE_URL)s

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""

_ENV_PY = """\
# alembic/env.py — DO NOT EDIT (regenerated by AgentFrame MigrationGenerator)
import glob
import importlib
import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool
from sqlmodel import SQLModel
from alembic import context

# Add project root to path so generated.models.* can be imported
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import all generated table models so Alembic can detect them
for _path in sorted(glob.glob("generated/models/*_table.py")):
    _module_name = _path.replace("/", ".").replace("\\\\", ".").replace(".py", "")
    try:
        importlib.import_module(_module_name)
    except Exception as e:
        print(f"Warning: could not import {_module_name}: {e}")

config = context.config

# Override sqlalchemy.url from environment variable
_db_url = os.environ.get("APP_DATABASE_URL") or os.environ.get("DATABASE_URL")
if _db_url:
    config.set_main_option("sqlalchemy.url", _db_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = SQLModel.metadata


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
"""

# Use single-quoted string to avoid conflict with triple-double-quote Mako syntax
_SCRIPT_MAKO = '''\
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
'''

_VERSIONS_GITKEEP = ""


class MigrationGenerator(BaseGenerator):
    """Generates the Alembic project structure (idempotent).

    Migration scripts themselves are created by `agentframe migrate`
    or the deploy pipeline — NOT by this generator.
    """

    def generate(self, graph: Graph) -> dict[str, str]:
        return {
            "../alembic.ini": _ALEMBIC_INI,
            "../alembic/env.py": _ENV_PY,
            "../alembic/script.py.mako": _SCRIPT_MAKO,
            "../alembic/versions/.gitkeep": _VERSIONS_GITKEEP,
        }
