from agentframe.generators.base import BaseGenerator
from agentframe.graph.store import Graph


def _has_provider(graph: Graph, provider: str) -> bool:
    return any(
        n.attrs.get("provider") == provider
        for n in graph.list_nodes("integration")
    )


def _get_app_title(graph: Graph) -> str:
    """Get app title from landing page or first page node."""
    pages = graph.list_nodes("page")
    landing = next((p for p in pages if p.id == "landing"), None)
    if landing:
        return landing.label
    if pages:
        return pages[0].label
    return "AgentFrame App"


def _render_main_prod(graph: Graph) -> str:
    entities = graph.list_nodes("entity")
    flows = graph.list_nodes("flow")

    has_google = _has_provider(graph, "google_oauth")
    has_email = _has_provider(graph, "email_magic_link")
    has_auth = has_google or has_email

    app_title = _get_app_title(graph)

    # Build import blocks
    crud_imports = "\n".join(
        f"from generated.routes.{e.id}_crud import router as {e.id}_crud_router"
        for e in sorted(entities, key=lambda n: n.id)
    )
    flow_imports = "\n".join(
        f"from generated.routes.{f.id}_flow import router as {f.id}_flow_router"
        for f in sorted(flows, key=lambda n: n.id)
    )

    auth_import = ""
    if has_google:
        auth_import = "from generated.middleware.google_auth import router as auth_router"
    elif has_email:
        auth_import = "from generated.middleware.email_auth import router as auth_router"

    # Build include_router calls
    crud_includes = "\n".join(
        f"app.include_router({e.id}_crud_router)"
        for e in sorted(entities, key=lambda n: n.id)
    )
    flow_includes = "\n".join(
        f"app.include_router({f.id}_flow_router)"
        for f in sorted(flows, key=lambda n: n.id)
    )

    auth_include = "app.include_router(auth_router)" if has_auth else ""
    csrf_middleware = (
        'app.add_middleware(CSRFMiddleware, secret_key=os.environ["SECRET_KEY"])'
        if has_auth else ""
    )
    session_middleware = (
        'app.add_middleware(SessionMiddleware, secret_key=os.environ["SECRET_KEY"])'
        if has_auth else ""
    )
    csrf_import = (
        "from generated.middleware.csrf import CSRFMiddleware\n"
        "from starlette.middleware.sessions import SessionMiddleware"
        if has_auth else ""
    )

    return f"""\
# main_prod.py — DO NOT EDIT (generated by AgentFrame ProdGenerator)
# Production entrypoint: no /mcp, no /_console.
# DB migrations run on startup via lifespan handler.
#
# NOTE: If you have custom routes in app/routes.py, add this import and include:
#   from app.routes import router as app_router
#   app.include_router(app_router)
import os
from pathlib import Path
from contextlib import asynccontextmanager
from dotenv import load_dotenv

load_dotenv()

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
{csrf_import}
{auth_import}
{crud_imports}
{flow_imports}
from agentframe.database.migrations import run_pending_migrations

# Auto-detect custom app routes
_has_app_routes = Path("app/routes.py").exists()
if _has_app_routes:
    from app.routes import router as app_router


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Run any pending Alembic migrations before accepting traffic.
    # This is what makes iterative deploys safe — deploy, then migrate in-process.
    run_pending_migrations()
    yield


app = FastAPI(title="{app_title}", lifespan=lifespan)


@app.get("/health")
def health():
    return {{"status": "ok"}}


{session_middleware}
{csrf_middleware}
{auth_include}
# Custom app routes (if app/routes.py exists)
if _has_app_routes:
    app.include_router(app_router)

{crud_includes}
{flow_includes}

# Static files (if static/ directory exists)
_static_dir = Path(__file__).parent / "static"
if _static_dir.exists():
    app.mount("/static", StaticFiles(directory=str(_static_dir)), name="static")
"""


class ProdGenerator(BaseGenerator):
    """Generates main_prod.py in the project root (one level above generated/)."""

    def generate(self, graph: Graph) -> dict[str, str]:
        return {
            "../main_prod.py": _render_main_prod(graph),
        }
